### ISSUE TITLE
Host text too long for single line in some terminal sizes

### ISSUE THREAD

**Issue by Kara-Zor-El** [devanlooches/rocketfetch#3]
![Screenshot_20211231_150530](https://user-images.githubusercontent.com/69772087/147837807-531419a4-0af9-41ef-a858-4ef78ddb92fd.png)
would be great if there were a way to have text wrap to the next line after the ascii art
PS. love this project and has been a huge help to me when looking for different ways of doing stuff for my own rust neofetch clone

**Comment by devanlooches** [comment]
Hello! Thank you for the feedback! How many characters do you propose to be the maximum before a line wrap be done?

**Comment by Kara-Zor-El** [comment]
I would say I would say the length of the string / 2 would probably be the best bet

**Comment by devanlooches** [comment]
Alright. I'll see what I can do. Thanks again for the feedback!

**Comment by devanlooches** [comment]
Hmm. That doesn't actually sound so great because at least on my computer the string is very short.

**Comment by devanlooches** [comment]
I think we should go with like a maximum number of characters

**Comment by devanlooches** [comment]
I just added line wrapping depending on the terminal size. Can you let me know if it works for you?

**Comment by Kara-Zor-El** [comment]
Hi, that works well now however there is a blank after the terminal module
![image](https://user-images.githubusercontent.com/69772087/150404832-3866eb9f-8661-4f3f-9414-09f0fd79b459.png)

**Comment by devanlooches** [comment]
I just pushed a new commit that should fix it.
I think it was because i did not add trims to the output.

**Comment by Kara-Zor-El** [comment]
hi, sorry for getting back so late to you, it is still doing the exact same thing. maybe specifically try doing `[variable].replace("\n", " ");` to make sure it isnt doing `\n` during it

**Comment by devanlooches** [comment]
Sorry it took me so long. I just pushed another update (on crates.io). Can you let me know if it fixed the problem?

**Comment by devanlooches** [comment]
I'm going to close this issue for now because I think I fixed it. 
You can reopen it if you think I'm wrong.
